define(["DQX/Utils", "DQX/Controls", "DQX/Msg", "DQX/Popup"],
    function (DQX, Controls, Msg, Popup) {
        var MetaData = {};


        MetaData.serverUrl="http://localhost:8000/app01";
        //MetaData.serverUrl="http://localhost/DQXServer/app";
        //MetaData.serverUrl="http://panoptes.cggh.org/sandbox/dqx_server_GenomeTrackViewer/app";

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Data source tables
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        //theMetaData1.database = 'pf21c';
        MetaData.database = 'pf30viewtracks';
        MetaData.tableAnnotation = 'pf3annot'; //Genome annotation

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Define the metadata that is generated by the client (NOTE: some of this stuff should move to the server)
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////


        //////// Information about the chromosomes
/*        MetaData.chromosomes = [
            { id: 'Pf3D7_01_v3', len: 0.640851 },
            { id: 'Pf3D7_02_v3', len: 0.947102 },
            { id: 'Pf3D7_03_v3', len: 1.067971 },
            { id: 'Pf3D7_04_v3', len: 1.200490 },
            { id: 'Pf3D7_05_v3', len: 1.343557 },
            { id: 'Pf3D7_06_v3', len: 1.418242 },
            { id: 'Pf3D7_07_v3', len: 1.445207 },
            { id: 'Pf3D7_08_v3', len: 1.472805 },
            { id: 'Pf3D7_09_v3', len: 1.541735 },
            { id: 'Pf3D7_10_v3', len: 1.687656 },
            { id: 'Pf3D7_11_v3', len: 2.038340 },
            { id: 'Pf3D7_12_v3', len: 2.271494 },
            { id: 'Pf3D7_13_v3', len: 2.925236 },
            { id: 'Pf3D7_14_v3', len: 3.291936 }
        ];
        $.each(MetaData.chromosomes, function (idx, chr) { chr.name = chr.id; });*/

        MetaData.showClusterData = false;

        MetaData.populations=[
            { freqid:'NRAF_WAF', name:"West Africa", color:DQX.Color(1,0,0) },
            { freqid:'NRAF_EAF', name:"East Africa", color:DQX.Color(0,0,1) }
            //{ freqid:'NRAF_SEA', name:"South-east Asia", color:DQX.Color(0,0.7,0.5) }
        ];

        MetaData.summaryFolder='Tracks-PfPopGen2.1';//Location of the summary data, relative to the base path defined by DQXServer
        MetaData.summaryConfig='Summ01';//ID of the summary configuration used


        //List of all the summary profiles displayed in the app
        MetaData.summaryProfiles=[
            { id:'GC300', name:"%GC" },
            { id:'Uniqueness', name:"Uniqueness" }
        ];


        // Empty placeholders: this info has not been obtained yet
        MetaData.customProperties = [];

        MetaData.findProperty = function(tableid, propid) {
            var rs = null;
            $.each(MetaData.customProperties, function(idx, propInfo) {
                if ((propInfo.tableid==tableid) && (propInfo.propid==propid))
                    rs =  propInfo;
            });
            if (rs!=null) return rs;
            DQX.reportError('Property {prop} not found for table {table}'.DQXformat({prop:propid, table: tableid}));
        }

        return MetaData;
    });
